#!/bin/env bash
# Install all dotfiles in their respective System locations
# usually via symlinks

function crate_link() {
  local target=$1
  local link_loc=$2

  if [[ -L "$link_loc" ]]; then
    return 0
  elif [[ -e "$link_loc" ]]; then
    echo "Error: $link_loc already exists." >&2
    return 1
  fi

  ln -sv "$(pwd)/$target" "$link_loc"
}

# Bash
crate_link "bashrc" ~/.bashrc
crate_link "bash_profile" ~/.bash_profile
crate_link "profile" ~/.profile

# Neovim
crate_link "nvim" ~/.config/nvim

# Vim
crate_link "vimrc" ~/.vimrc

# Emacs (not that I would actually use it, but anyway)
crate_link "emacs" ~/.emacs

# Git
crate_link "gitconfig" ~/.gitconfig

# XCompose
crate_link "XCompose" ~/.XCompose

# GNU Debugger
crate_link "gdbinit" ~/.gdbinit

# SSH Config
crate_link "ssh-config" ~/.ssh/config

# Kitty Terminal
crate_link "kitty" ~/.config/kitty

# Sway
crate_link "sway" ~/.config/sway
crate_link "rofi" ~/.config/rofi
crate_link "waybar" ~/.config/waybar
